project:
  type: website
  output-dir: docs

website:
  title: "web_stats"
  navbar:
    left:
      - href: "https://wlperry.github.io/index.html"
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true